replicaCount: 2

image:
  repository: ghcr.io/soluto/linkerd-disable-injection-mutation-webhook 
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443
  metricsPort: 8081

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

serviceMonitor:
  enabled: false

imagePullPolicy: Always