apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "linkerd-disable-injection-mutation-webhook.fullname" . }}
  labels:
{{ include "linkerd-disable-injection-mutation-webhook.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "linkerd-disable-injection-mutation-webhook.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "linkerd-disable-injection-mutation-webhook.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: tls-secret-volume
          secret:
            secretName: {{ include "linkerd-disable-injection-mutation-webhook.fullname" . }}-tls
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: tls-secret-volume
              mountPath: /app/ssl
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
            - name: metrics
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              scheme: HTTPS
              port: 8443
          readinessProbe:
            httpGet:
              path: /
              scheme: HTTPS
              port: 8443
          resources:
            {{- toYaml .Values.resources | nindent 12 }}