apiVersion: v1
kind: Service
metadata:
  name: {{ include "linkerd-disable-injection-mutation-webhook.fullname" . }}
  labels:
{{ include "linkerd-disable-injection-mutation-webhook.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8443
      protocol: TCP
      name: https
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "linkerd-disable-injection-mutation-webhook.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
