name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GHCR
        uses: docker/login-action@v1 
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_WRITER }}
          registry: ghcr.io
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/soluto/linkerd-disable-injection-mutation-webhook:latest
          push: true
          

